### ISSUE TITLE
Makefile_M issue

### ISSUE THREAD

**Issue by dpolychr** [lorrainea/mim#2]
I get this error:

>make -f Makefile_M
g++ -g++-7 -g -fopenmp -D_USE_OMP -msse4.2 -O3 -fomit-frame-pointer -funroll-loops  -c -std=c++11 -I ./ mim.cc -c -std=c++11 -I ./ mim.cc 
clang: error: unknown argument: '-g++-7'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
make: *** [mim.o] Error 1

I think it is easily solved right?

**Comment by dpolychr** [comment]
OK, changing the compiler at the Makefile worked, but i got those warnings:

g++-7 -g -fopenmp -D_USE_OMP -msse4.2 -O3 -fomit-frame-pointer -funroll-loops  -c -std=c++11 -I ./ mim.cc -c -std=c++11 -I ./ mim.cc 
g++-7 -g -fopenmp -D_USE_OMP -msse4.2 -O3 -fomit-frame-pointer -funroll-loops  -c -std=c++11 -I ./ mim.cc -c -std=c++11 -I ./ extend.cc 
g++-7 -g -fopenmp -D_USE_OMP -msse4.2 -O3 -fomit-frame-pointer -funroll-loops  -c -std=c++11 -I ./ mim.cc -c -std=c++11 -I ./ utils.cc 
g++-7 -g -fopenmp -D_USE_OMP -msse4.2 -O3 -fomit-frame-pointer -funroll-loops  -c -std=c++11 -I ./ mim.cc -c -std=c++11 -I ./ qgrams.cc 
g++-7 -g -fopenmp -D_USE_OMP -msse4.2 -O3 -fomit-frame-pointer -funroll-loops  -c -std=c++11 -I ./ mim.cc -c -std=c++11 -I ./ overlaps.cc 
g++-7 -g -fopenmp -D_USE_OMP -msse4.2 -O3 -fomit-frame-pointer -funroll-loops  -c -std=c++11 -I ./ mim.cc  -o mim mim.o extend.o utils.o qgrams.o overlaps.o  -std=c++11 -I ./ 
g++-7: warning: mim.o: linker input file unused because linking not done
g++-7: warning: extend.o: linker input file unused because linking not done
g++-7: warning: utils.o: linker input file unused because linking not done
g++-7: warning: qgrams.o: linker input file unused because linking not done
g++-7: warning: overlaps.o: linker input file unused because linking not done

**Comment by lorrainea** [comment]
Does removing -c solve anything?

**Comment by dpolychr** [comment]
If i remove -c from and run:

g++-7 -g -fopenmp -D_USE_OMP -msse4.2 -O3 -fomit-frame-pointer -funroll-loops  -std=c++11 -I ./ mim.cc  -std=c++11 -I ./ mim.cc

I get a whole bunch of errors...

Undefined symbols for architecture x86_64:
  "decode_switches(int, char**, TSwitch*)", referenced from:
      _main in ccwZvTv3.o
      _main in ccOzAvA8.o
  "remove_overlaps(std::vector<MimOcc, std::allocator<MimOcc> >*, TSwitch)", referenced from:
      _main in ccwZvTv3.o
      _main in ccOzAvA8.o
  "find_maximal_exact_matches(unsigned int, unsigned char*, unsigned char*, std::vector<QGramOcc, std::allocator<QGramOcc> >*, TSwitch)", referenced from:
      _main in ccwZvTv3.o
      _main in ccOzAvA8.o
  "find_maximal_inexact_matches(TSwitch, unsigned char*, unsigned char*, std::vector<QGramOcc, std::allocator<QGramOcc> >*, std::vector<MimOcc, std::allocator<MimOcc> >*)", referenced from:
      _main in ccwZvTv3.o
      _main in ccOzAvA8.o
  "usage()", referenced from:
      _main in ccwZvTv3.o
      _main in ccOzAvA8.o
  "gettime()", referenced from:
      _main in ccwZvTv3.o
      _main in ccOzAvA8.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

**Comment by lorrainea** [comment]
Can you run the code with just the previous warnings that were given ?

**Comment by dpolychr** [comment]
No

**Comment by dpolychr** [comment]
I have installed it on our Linux server and everything went smoothly :)
